model_path: ../models/best.onnx
video_path: ../video/longchau.mp4
output_path: ../video/longchau_cpp_output.mp4
execution_device: auto   # auto | gpu | cpu
gpu_device_id: 0

det_conf: 0.5
det_iou: 0.50
input_width: 640
input_height: 640

show_window: false
window_name: YOLO ONNX + Tracker (C++)
draw_detections: true
draw_tracks: true
baseline_output_path: ../video/cpp_baseline.json
tracker_type: botsort

track_high_thresh: 0.45
track_low_thresh: 0.15
new_track_thresh: 0.75
track_buffer: 450
match_thresh: 0.72
proximity_thresh: 0.55
appearance_thresh: 0.32
second_association_thresh: 0.35
unconfirmed_association_thresh: 0.7
cmc_method: ecc
reid_recovery_enabled: true
reid_recovery_proximity_thresh: 0.88
reid_recovery_appearance_thresh: 0.35
reid_recovery_thresh: 0.40
reid_model_path: ../models/osnet_x0_5_msmt17.onnx
reid_execution_device: auto   # optional override for ReID
cmc_interval: 1
cmc_max_side: 960
reid_max_detections: 4096

